# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_APP_CATALOG: s1pro-core-applicative-catalog

app-catalog-build-master:
  stage: module
  script:
    - cd applicative-catalog
    - dockerbuild -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_APP_CATALOG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_APP_CATALOG"
  only:
    - master

app-catalog-build:
  stage: module
  script:
    - alias
    - cd applicative-catalog
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_APP_CATALOG:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_APP_CATALOG:$CI_COMMIT_REF_SLUG"
  except:
    - master
