# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  MODULE_MQI_SERVER: s1pro-core-mqi-server

mqi-server-build:
  stage: module
  script:
    - cd mqi-server
    - dockerbuild --cache-from registry.tools.s1pdgs.eu/werum/processing/s1pro-core:final -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_MQI_SERVER:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$MODULE_MQI_SERVER:$CI_COMMIT_REF_SLUG"
